# MNM Fasteners Agent - Installation Script
# Run as Administrator

#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"

Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  MNM Fasteners Agent Installer" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Configuration
$InstallPath = "C:\Program Files\MNMAgent"
$DataPath = "C:\ProgramData\MNMAgent"
$PythonMinVersion = [version]"3.10.0"

# Check Python
Write-Host "Checking Python installation..." -ForegroundColor Yellow
try {
    $pythonVersion = & python --version 2>&1
    $versionString = $pythonVersion -replace "Python ", ""
    $currentVersion = [version]$versionString
    
    if ($currentVersion -lt $PythonMinVersion) {
        Write-Host "Error: Python $PythonMinVersion or higher is required. Found: $versionString" -ForegroundColor Red
        exit 1
    }
    Write-Host "Found Python $versionString" -ForegroundColor Green
} catch {
    Write-Host "Error: Python not found. Please install Python 3.10 or higher." -ForegroundColor Red
    exit 1
}

# Create directories
Write-Host ""
Write-Host "Creating directories..." -ForegroundColor Yellow

$directories = @(
    $InstallPath,
    "$DataPath\logs",
    "$DataPath\data"
)

foreach ($dir in $directories) {
    if (!(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
        Write-Host "  Created: $dir" -ForegroundColor Gray
    }
}

# Create virtual environment
Write-Host ""
Write-Host "Setting up Python virtual environment..." -ForegroundColor Yellow

$venvPath = "$InstallPath\venv"
if (!(Test-Path $venvPath)) {
    & python -m venv $venvPath
    Write-Host "  Virtual environment created" -ForegroundColor Green
}

# Activate virtual environment and install packages
Write-Host ""
Write-Host "Installing dependencies..." -ForegroundColor Yellow

$pipPath = "$venvPath\Scripts\pip.exe"
$pythonPath = "$venvPath\Scripts\python.exe"

# Upgrade pip
& $pipPath install --upgrade pip

# Get script directory (where the agent code is)
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentRoot = Split-Path -Parent $ScriptDir

# Install the agent package
& $pipPath install -e "$AgentRoot[windows]"

Write-Host "  Dependencies installed" -ForegroundColor Green

# Create configuration file
Write-Host ""
Write-Host "Creating configuration..." -ForegroundColor Yellow

$configPath = "$DataPath\config.env"
if (!(Test-Path $configPath)) {
    $configTemplate = @"
# MNM Fasteners Agent Configuration
# Generated by installer

# Agent Identity - Change these!
AGENT_ID=mnm-agent-001
AGENT_SECRET=CHANGE_ME_TO_SECURE_SECRET

# Backend Server Connection - Update with your server details
BACKEND_URL=wss://api.yourbackend.com/agent/ws
BACKEND_API_URL=https://api.yourbackend.com/api/v1
BACKEND_API_KEY=CHANGE_ME_TO_YOUR_API_KEY

# Polling Configuration
POLLING_INTERVAL=30
POLLING_ENABLED=true

# Sage 50 Configuration - Update with your Sage 50 company path
SAGE50_COMPANY_PATH=C:\ProgramData\Sage\Accounts\2024\Company.001
SAGE50_USERNAME=
SAGE50_PASSWORD=

# Logging
LOG_LEVEL=INFO
LOG_FILE=$DataPath\logs\agent.log

# Agent Settings
MAX_RETRY_ATTEMPTS=3
RETRY_DELAY_SECONDS=5
HEARTBEAT_INTERVAL=60
TASK_TIMEOUT=300
"@
    $configTemplate | Out-File -FilePath $configPath -Encoding UTF8
    Write-Host "  Configuration file created: $configPath" -ForegroundColor Green
    Write-Host "  IMPORTANT: Edit this file with your actual settings!" -ForegroundColor Yellow
} else {
    Write-Host "  Configuration file already exists" -ForegroundColor Gray
}

# Create batch file for easy running
Write-Host ""
Write-Host "Creating launcher scripts..." -ForegroundColor Yellow

$runBatch = @"
@echo off
cd /d "$InstallPath"
"$pythonPath" -m agent.cli %*
"@
$runBatch | Out-File -FilePath "$InstallPath\mnm-agent.bat" -Encoding ASCII

# Add to PATH
$envPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($envPath -notlike "*$InstallPath*") {
    [Environment]::SetEnvironmentVariable("Path", "$envPath;$InstallPath", "Machine")
    Write-Host "  Added to system PATH" -ForegroundColor Green
}

Write-Host ""
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "  Installation Complete!" -ForegroundColor Green
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Edit configuration: $configPath" -ForegroundColor White
Write-Host "2. Test the agent: mnm-agent status" -ForegroundColor White
Write-Host "3. Test Sage 50: mnm-agent test-sage" -ForegroundColor White
Write-Host "4. Install as service: mnm-agent install" -ForegroundColor White
Write-Host "5. Start service: mnm-agent start" -ForegroundColor White
Write-Host ""
Write-Host "For help: mnm-agent --help" -ForegroundColor Gray

